In [47]:
l=[2,3,4,5]
print(type(l))
print(l)

<class 'list'>
[2, 3, 4, 5]


In [48]:

l.append(7)
print(l)

[2, 3, 4, 5, 7]


In [49]:
j=[5,6,8]
l.extend(j)
print(l)

[2, 3, 4, 5, 7, 5, 6, 8]


In [50]:
print(len(l))

8


In [51]:
l.insert(2, 10)

In [52]:
print(l)

[2, 3, 10, 4, 5, 7, 5, 6, 8]


In [53]:
g=5.0
print(type(g))

<class 'float'>


In [54]:
g=int(g)
print(type(g))
print(g)

<class 'int'>
5


In [55]:
g=str(g)
print(type(g))
print(g)

<class 'str'>
5


In [56]:
import  numpy as np



In [57]:
print(np.__version__)

2.3.5


In [58]:
arr=[1,2,3,4]
print(type(arr))

<class 'list'>


In [59]:
arr1=arr * 2
print(arr1)

[1, 2, 3, 4, 1, 2, 3, 4]


In [60]:
l=[]
for i in arr:
    l.append(i*3)
print(l)

[3, 6, 9, 12]


In [61]:
print(arr)
print(type(arr))

[1, 2, 3, 4]
<class 'list'>


In [62]:
arr=np.array(arr)
print(type(arr))
print(arr)

<class 'numpy.ndarray'>
[1 2 3 4]


In [63]:
print(arr*2)

[2 4 6 8]


In [65]:
brr=np.array([1,2,3,4])
print(arr+brr)

[2 4 6 8]
