## Linear Algebra  
Intuition

AI models = matrix transformations

- **Data** → matrix  
- **Weights** → matrix  
- **Output** = matrix multiplication

Core operation: Matrix Multiplication

\[
C_{ij} = \sum_k A_{ik} B_{kj}
\]

Where:
- \(A\) and \(B\) are matrices

In [4]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

C = A @ B
print(C)

[[19 22]
 [43 50]]


In [7]:
np.dot(A, B)          # same as @


array([[19, 22],
       [43, 50]])

In [8]:
np.linalg.inv(A)      # inverse


array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [9]:
np.linalg.det(A)      # determinant


np.float64(-2.0000000000000004)

In [10]:
np.linalg.eig(A)      # eigenvalues

EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))