In [1]:
# Question 1
import numpy as np
arr=np.array([
              [1,2,3],
              [4,5,6],        
              [7,8,9]])
print(arr)

print(arr.shape)

print(arr.ndim)

print(arr.dtype)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
2
int64


In [2]:
#Question 2
array=np.arange(0,20,2)
print(array)


[ 0  2  4  6  8 10 12 14 16 18]


In [3]:

a = np.arange(15).reshape(3, 5) # reshape the array to 3 rows and 5 columns
print(a)
print(a.shape) # print the shape of the array
print(a.ndim) # print the number of dimensions
print(a.dtype.name) # print the data type name
print(a.itemsize) # print the size of each element
print(a.size) # print the total number of elements
print(type(a)) # print the type of the array
b = np.array([6, 7, 8]) 
print(b) # print the array
print(type(b)) # print the type of the array

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
(3, 5)
2
int64
8
15
<class 'numpy.ndarray'>
[6 7 8]
<class 'numpy.ndarray'>


In [4]:
A = np.ones((3, 3))
b = np.array([1, 2, 3])

print(A + b) 
print("the  result of A * b ")
print(A * b)

[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]
the  result of A * b 
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]
